config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # ========= ユーザー(user)のルーティング ================

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resource 'contacts', only: [:new, :create] do
    get 'thanks' => 'contacts#thanks'
  end

  scope module: :user do
    resources 'shops', only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources 'reviews', only: [:create, :destroy, :index]
      resource 'bookmarks', only: [:create, :destroy]
    end

    get 'search' => 'shops#search'
    get 'rank'=> 'shops#rank'
    get 'hot'=> 'shops#hot'

    resources :tags do
    get 'shops', to: 'shops#tag_search'
    end

    resources 'users', only: [:show, :edit, :update] do
      member do
        get :followings, :followers
      end
    end


    get 'user/quit_confirm' => 'users#quit_confirm'
    patch 'user/quit' => 'users#quit'

    resources 'relationships', only: [:create, :destroy]

    resources 'tweets', only: [:create, :destroy, :new, :show] do
      resource :likes, only: [:create, :destroy]
      resources :tweet_comments, only: [:create, :destroy]
    end



    resources :notifications, only: :index

  end


# ========= 管理者側(admin)のルーティング ================
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do
    resources 'users', only: [:index, :show, :edit, :update]
    resources 'contacts', only: [:index, :update]
    get 'contacts_sort' => 'contacts#contacts_sort'
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if @user.is_valid == true
        status = '有効'
      else
        status = '無効'
      end
      flash[:notice] = "ステータスを#{status}に変更しました。"
      redirect_to edit_admin_user_path(@user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:is_valid)
  end

end

app/controllers/user/application_controller.rb
class User::ApplicationController  < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :search, :rank, :hot, :tag_search]
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < User::ApplicationController

  def create
    @shop = Shop.find(params[:shop_id])
    bookmark = @shop.bookmarks.new(user_id: current_user.id)
    if bookmark.save
      @shop.create_notification_bookmark!(current_user)
    else
      redirect_to request.referer
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    bookmark = @shop.bookmarks.find_by(user_id: current_user.id)
    if bookmark.present?
        bookmark.destroy
    else
        redirect_to request.referer
    end
  end
  
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to thanks_contacts_path
    else
      render :new
    end
  end

  def thanks
  end
  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    like = current_user.likes.new(tweet_id: tweet.id)
    like.save
    redirect_to request.referer 
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    like = current_user.likes.find_by(tweet_id: tweet.id)
    like.destroy
    redirect_to request.referer 
  end
  
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController <  User::ApplicationController

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < User::ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    user.create_notification_follow!(current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < User::ApplicationController

  def index
    @shop = Shop.find(params[:shop_id])
    @review = Review.new
    @reviews = @shop.reviews
    if @shop.reviews.blank?
      @average_review = 0
    else
      @average_review = @shop.reviews.average(:rate).round(2)
    end
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @review = @shop.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      @shop.create_notification_review!(current_user, @review.id)
      @shop.rate_average = Review.where(shop_id: @shop.id).average(:rate)
      @shop.save
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:review_text, :rate)
  end

end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  before_action :set_tweet

  def set_tweet
    @tag_list = Tag.includes(:tagmaps).all
    @tweets = Tweet.includes(:user).all
    @tweet = Tweet.new
    if user_signed_in?
      @mytweets = Tweet.where(user_id: current_user.following).or(Tweet.where(user_id: current_user.id))
    end
  end

  def index
    @tag_list = Tag.includes(:tagmaps).all
    @shops = Shop.includes(:reviews).all.page(params[:page]).reverse_order
    @tweets = Tweet.includes(:user).all
    @tweet = Tweet.new

  end

  def show
    @shop = Shop.includes(:user, reviews: :user).find(params[:id])
    @shop_tags = @shop.tags
    @user = @shop.user
    @review = Review.new
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    tag_list = params[:shop][:tag_name].split(/[[:blank:]]+/)
    if @shop.save
      @shop.save_tag(tag_list)
      # params[:shop][:post_image].each do |a|
      #     @post_image = @shop.shop_images.create!(post_image: a, shop_id: @shop.id)
      # end
      redirect_to shops_path
    else
      render 'new'
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    unless user_signed_in? && current_user.id == @shop.user.id
      redirect_to action: :index
    end
  end

  def update
    @shop = Shop.find(params[:id])
    tag_list = params[:shop][:tag_name].split(/[[:blank:]]+/)
    if @shop.update(shop_params)
      @shop.save_tag(tag_list)
      redirect_to shop_path(@shop.id)
    else
      render 'edit'
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path
  end

  def search
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @shops = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @shops += Shop.joins(tagmaps: :tag).where(["shop_name like? OR address like? OR tag_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
    @shops.uniq!
    @shops = Kaminari.paginate_array(@shops).page(params[:page])
    render 'index'
  end

  def rank
    @shops = Shop.all.includes(:reviews).order(rate_average: 'asc').page(params[:page]).reverse_order
    render 'index'
  end

  def hot
    @shops = Shop.joins(:reviews).where(created_at: Date.today.ago(7.days)..Date.today).group(:id).order("count(*) asc").page(params[:page]).reverse_order
    render 'index'
  end


  def tag_search
    @tag_list = Tag.includes(:tagmaps, tagmaps: :shop).all
    @tag = Tag.find(params[:tag_id])
    @shops = @tag.shops.includes(:tagmaps, tagmaps: :tag).all
  end

  private

  def shop_params
     params.require(:shop).permit(:shop_name, :shop_image, :introduction, :address, :tell, :holiday, :latitude, :longitude, :business_hours, post_images_images: [])
  end

end

app/controllers/user/tweet_comments_controller.rb
class User::TweetCommentsController < ApplicationController

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = current_user.tweet_comments.new(tweet_comment_params)
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet)
  end

  def destroy
    TweetComment.find_by(id: params[:id], tweet_id: params[:tweet_id]).destroy
    redirect_to tweet_path(params[:tweet_id])
  end

  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment)
  end
  
end

app/controllers/user/tweets_controller.rb
class User::TweetsController <User::ApplicationController

  def new
    @tweet = Tweet.new
  end

  def create
    @shop = Shop.new
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_back(fallback_location: root_path)
  end

private
  def tweet_params
    params.require(:tweet).permit(:user_id, :tweet)
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::ApplicationController

  def show
    @user = User.find(params[:id])
    @shops = @user.shops.includes(:reviews).all.order(created_at: "DESC")
    @bookmarks = Bookmark.includes(:shop,shop: :user).where(user_id: @user.id).page(params[:page]).per(8)
    @tweet = Tweet.new
    @tweets = Tweet.where(user_id: @user.following)
    @mytweets = Tweet.where(user_id: @user.id)
    @reviews = Review.includes(:user, :shop).where(user_id: @user).page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
    unless user_signed_in? && current_user.id == @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user.id)
      else
        render 'edit'
      end
  end

  def quit_confirm
  end

  def quit
    current_user.update(is_valid: false)
    sign_out(current_user)
  end

  def followings
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの編集はできません。'
    end
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/users/edit.html.erb
<div class='container'>
  <div class="row g-3 mt-5 mb-5">
    <div class="form-area col-lg-6 p-5 offset-lg-3 col-md-12 mb-5">

      <div class='mb-5 float-right'>
        <%= link_to '退会する', user_quit_confirm_path, class: "btn btn-outline-dark btn-sm"  %>
      </div>

      <h5>アカウント情報</h5>

      <div class='errors-area p-2'>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のエラーが発生しました</br>
          <% @user.errors.full_messages.each do |message| %>
            <li>※&nbsp;<%= message %></li>
          <% end %>
        <% end %>
      </div>

      <%= form_with model: @user, local:true do |f| %>

        <div class="field form-group">
          <%= f.label :'アカウント名' %><br />
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="field form-group">
          <%= f.label :'プロフィール画像' %><br />
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", id: "user_img_prev", class: "rounded-circle", style: "height: 80px; width:80px;" %><br>
          </br>
          <%= f.attachment_field :profile_image, class: "form-control-file" %>
        </div>

        <div class="field form-group">
          <%= f.label :'自己紹介文' %><br />
          <%= f.text_area :introduction, class: "form-control" %>
        </div>

        <%= f.submit '更新', class: 'btn btn-outline-dark' %>
      <% end %>

    </div>
  </div>
</div>

app/views/user/users/followers.html.erb
<div class='container'>
  <div class="row g-3 mt-5">
    <div class="form-area col-md-8 col-12 m-auto p-5">
      <h2 class="text-center mb-5">フォロワー</h2>
      <% if @user.followers.length > 0 %>
        <table class="table table-sm w-75 m-auto">
          <% @user.followers.each do |user| %>
            <tr>
              <td class="text-center" style="width: 15%;">
              <%= link_to user_path(user.id), data: {"turbolinks" => false} do %>
                 <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %>
              </td>
              <td  style="width: 55%;">
                <%= link_to user_path(user.id), data: {"turbolinks" => false} do %>
                   <%= user.name %>
                <% end %>
              </td>
              <td  style="width: 30%;">
                <%= render 'user/relationships/follow_button', user: user %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <% if @user == current_user %>
          たくさんレビューして、フォロワーを増やそう！</br>
          <%= link_to 'お店紹介一覧を見る', shops_path %>
        <% else %>
          ユーザーがいません
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/followings.html.erb
<div class='container'>
  <div class="row g-3 mt-5">
    <div class="form-area col-md-8 col-12 m-auto p-5">
      <h2 class="text-center mb-5">フォロワー</h2>
      <% if @user.following.length > 0 %>
        <table class="table table-sm w-75 m-auto">
          <% @user.following.each do |user| %>
            <tr>
              <td class="text-center" style="width: 15%;">
              <%= link_to user_path(user.id), data: {"turbolinks" => false} do %>
                 <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %>
              </td>
              <td  style="width: 55%;">
                <%= link_to user_path(user.id), data: {"turbolinks" => false} do %>
                   <%= user.name %>
                <% end %>
              </td>
              <td  style="width: 30%;">
                <%= render 'user/relationships/follow_button', user: user %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
          <% if @user == current_user %>
            ユーザーがいません
            いいお店を紹介しているアカウントをフォローしよう！</br>
            <%= link_to 'お店一覧を見る', shops_path %>
          <% else %>
            ユーザーがいません
          <% end %>
      <% end %>
      </div>
  </div>
</div>

app/views/user/users/quit.html.erb
<div class="container">
  ご利用いただきありがとうございました。
</div>

app/views/user/users/quit_confirm.html.erb
<div class='container'>
  <div class="row g-3 mt-5">
    <div class="form-area col-lg-6 p-5 offset-md-3">
      <h5>本当に退会しますか？</h5>
      <h6 class="text-center mt-5">
      <%= link_to '退会する', user_quit_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"} %>
      &nbsp;・&nbsp;
      <%= link_to '退会しない', shops_path %>
      </h6>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'homes/top_link' %>
    <div class="col-md-3 text-center mt-5">
      <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpeg", class: 'rounded-circle' %>
      <h1><%= @user.name %></h1>
      <%= render 'user/relationships/follow_button', user: @user %>
      <% if user_signed_in? %>
        <% if current_user.id == @user.id.to_i %>
          <%= link_to '編集', edit_user_path(@user.id), class: "btn btn-outline-dark btn-sm pl-5 pr-5" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-9 mt-5 col-12">
      <div class="follow-link">
        <table>
          <tr class="test-center">
            <th class="text-center" style='width: 150px;'><%= link_to followings_user_path(@user) do %>follow<% end %></th>
            <th class="text-center" style='width: 150px;'><%= link_to followers_user_path(@user) do %>follower<% end %></th>
          </tr>
          <tr>
            <td class="text-center"><%= link_to @user.following.count, followings_user_path(@user) %></td>
            <td class="text-center"><%= link_to @user.followers.count, followers_user_path(@user) %></td>
          </tr>
        </table>
      </div>
    <% if @user.introduction != nil %>
      <div class="col-md-9">
        <div class="introduction-area border border-secondary mt-4 p-3" style="height: 140px;">
          <%= @user.introduction %>
        </div>
      </div>
    <% end %>
    </div>
  </div>

<!------------main------------>

  <ul class="nav nav-tabs tabnav mt-5">
    <li class="nav-item">
      <a class="nav-link active" href="#shops">
        <span class='d-none d-lg-block'>投稿一覧</span>
        <span class='d-md-block d-lg-none'><i class="fas fa-utensils"></i></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#tweets">
        <span class='d-none d-lg-block'>つぶやき</span>
        <span class='d-md-block d-lg-none'><i class="far fa-comments"></i></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#bookmarks">
        <span class='d-none d-lg-block'>Bookmark</span>
        <span class='d-md-block d-lg-none'><i class="fas fa-bookmark"></i></span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#reviews">
        <span class='d-none d-lg-block'>Review</span>
        <span class='d-md-block d-lg-none'><i class="fas fa-pencil-alt"></i></span>
      </a>
      
    </li>
  </ul>

  <div class="tabcontent">
<!------------shops------------>
    <div id="shops" role="tabpanel" aria-labelledby="shops-tab">
      <div class="col-12 text-center mt-5 mb-3">
        <%= link_to 'お店を紹介する', new_shop_path, class: "btn btn-outline-success pl-5 pr-5" %>
      </div>
      <div class="row mt-5">
        <% if @shops.count == 0 %>
          <div class='col-10 mt-2 ml-5 mr-5'>
            <h6 class=" p-5 border">まだ投稿はありません</h6>
          </div>
        <% else %>
          <% @shops.each do |shop| %>
            <div class="col-lg-4 col-md-12">
              <div class="card cols-1 cols-md-2 cols-lg-3">
                <div class="card-header p-0">
                  <div class="zoomInText">
                    <%= link_to shop_path(shop.id) do %>
                     <span class="mask">
                        <%= attachment_image_tag shop, :shop_image, size: '200x200', format: 'jpeg', class: "card-img" %>
                        <span class="cap">
                          <h4 class="shop-name"><%= shop.shop_name %></h4></br>
                          <h6 class="fas fa-star">&nbsp;
                            <% if shop.rate_average == nil %>
                              評価なし
                            <% else %>
                              <%= shop.rate_average.round(1) %>
                            <% end %>
                          </h6>
                          </br>
                          <h6 class="fas fa-comment-dots">&emsp;<%= shop.reviews.size %></h6>
                        </span>
                      </span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
<!------------tweets------------>
    <div id="tweets" role="tabpanel" aria-labelledby="tweets">
      <% if user_signed_in? %>
        <div class="row mt-5">
          <div class="col-12 text-center">
            <%= link_to 'つぶやく', new_tweet_path, class: "btn btn-outline-success pl-5 pr-5" %>
          </div>
          <div class="col-md-6 col-12 mt-5">
            <% if current_user == @user %>
              <h4 class="col-12 text-center mb-4">my tweets</h4>
            <% else %>
              <h4 class="col-12 text-center mb-4">my tweets</h4>
            <% end %>

            <%= render 'user/tweets/index', tweets: @mytweets %>
          </div>
          <div class="col-md-6 col-12 mt-5">
            <h4 class="col-12 text-center mb-4">follow tweets</h4>
            <%= render 'user/tweets/index', tweets: @tweets %>
          </div>
        </div>
      <% else %>
        <h6 class="mx-auto m-3 p-5 border">
          ログイン後に閲覧いただけます。
          </br>
          <i class="fas fa-sign-in-alt mt-5"><%= link_to ' login', new_user_session_path %></i>
          <div class='mt-2' style='font-size: 15px;'>
            ご登録がまだの方は<%= link_to 'こちら', new_user_registration_path, class: 'text-success font-weight-bold' %>から
          </div>
        </h6>
      <% end %>
    </div>
<!------------bookmarks------------>
    <div id="bookmarks" role="tabpanel" aria-labelledby="bookmarks-tab">
      <div class="row m-5">
        <%= render 'user/bookmarks/bookmark_list', bookmarks: @bookmarks %>
      </div>
    </div>
<!------------review------------>
    <div id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
      <div class="row m-5">
        <div class="col-12 mb-5">
          <h4 class="mb-4 pb-2 border-bottom">レビューした記事</h4>
          <% if @reviews.count ==  0 %>
            <h6 class="mx-auto m-3 p-5 border">まだレビューした記事はありません。</h6>
          <% else %>
            <div class="scroll-list jscroll">
              <% @reviews.each do |review| %>
                <div class='row border-bottom mb-2'>
                  <div class="col-md-4 col-12">
                    <%= link_to shop_path(review.shop.id) do %>
                      <%= attachment_image_tag review.shop, :shop_image, size: '300x200', format: 'jpeg',class: 'img-fluid', style: 'object-fit: cover;'%></br>
                      <%= review.shop.shop_name %>
                    <% end %>
                  </div>
                  <div class="col-md-7 col-12">
                    <li><%= review.review_text %></li>
                    <li><%= review.created_at.strftime('%y/%m/%d') %></li>
                  </div>
                  <div class="col-md-1 col-12">
                    <% if review.user == current_user %>
                      <%= link_to shop_review_path(review.shop, review), method: :delete, remote: true do %>
                        <i class="fas fa-times-circle"></i>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <div class="scroll-area">
              <%= paginate @reviews %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>