config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # ========= ユーザー(user)のルーティング ================

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'homes#top'
  get 'about' => 'homes#about'
  resource 'contacts', only: [:new, :create] do
    get 'thanks' => 'contacts#thanks'
  end

  scope module: :user do
    resources 'shops', only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources 'reviews', only: [:create, :destroy, :index]
      resource 'bookmarks', only: [:create, :destroy]
    end

    get 'search' => 'shops#search'
    get 'rank'=> 'shops#rank'
    get 'hot'=> 'shops#hot'

    resources :tags do
    get 'shops', to: 'shops#tag_search'
    end

    resources 'users', only: [:show, :edit, :update] do
      member do
        get :followings, :followers
      end
    end


    get 'user/quit_confirm' => 'users#quit_confirm'
    patch 'user/quit' => 'users#quit'

    resources 'relationships', only: [:create, :destroy]

    resources 'tweets', only: [:create, :destroy, :new, :show] do
      resource :likes, only: [:create, :destroy]
      resources :tweet_comments, only: [:create, :destroy]
    end



    resources :notifications, only: :index

  end


# ========= 管理者側(admin)のルーティング ================
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do
    resources 'users', only: [:index, :show, :edit, :update]
    resources 'contacts', only: [:index, :update]
    get 'contacts_sort' => 'contacts#contacts_sort'
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :tweet, presence: true, length: { maximum: 140 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if @user.is_valid == true
        status = '有効'
      else
        status = '無効'
      end
      flash[:notice] = "ステータスを#{status}に変更しました。"
      redirect_to edit_admin_user_path(@user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:is_valid)
  end

end

app/controllers/user/application_controller.rb
class User::ApplicationController  < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :search, :rank, :hot, :tag_search]
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < User::ApplicationController

  def create
    @shop = Shop.find(params[:shop_id])
    bookmark = @shop.bookmarks.new(user_id: current_user.id)
    if bookmark.save
      @shop.create_notification_bookmark!(current_user)
    else
      redirect_to request.referer
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    bookmark = @shop.bookmarks.find_by(user_id: current_user.id)
    if bookmark.present?
        bookmark.destroy
    else
        redirect_to request.referer
    end
  end
  
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to thanks_contacts_path
    else
      render :new
    end
  end

  def thanks
  end
  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    like = current_user.likes.new(tweet_id: tweet.id)
    like.save
    redirect_to request.referer 
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    like = current_user.likes.find_by(tweet_id: tweet.id)
    like.destroy
    redirect_to request.referer 
  end
  
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController <  User::ApplicationController

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < User::ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    user.create_notification_follow!(current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < User::ApplicationController

  def index
    @shop = Shop.find(params[:shop_id])
    @review = Review.new
    @reviews = @shop.reviews
    if @shop.reviews.blank?
      @average_review = 0
    else
      @average_review = @shop.reviews.average(:rate).round(2)
    end
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @review = @shop.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      @shop.create_notification_review!(current_user, @review.id)
      @shop.rate_average = Review.where(shop_id: @shop.id).average(:rate)
      @shop.save
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:review_text, :rate)
  end

end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  before_action :set_tweet

  def set_tweet
    @tag_list = Tag.includes(:tagmaps).all
    @tweets = Tweet.includes(:user).all
    @tweet = Tweet.new
    if user_signed_in?
      @mytweets = Tweet.where(user_id: current_user.following).or(Tweet.where(user_id: current_user.id))
    end
  end

  def index
    @tag_list = Tag.includes(:tagmaps).all
    @shops = Shop.includes(:reviews).all.page(params[:page]).reverse_order
    @tweets = Tweet.includes(:user).all
    @tweet = Tweet.new

  end

  def show
    @shop = Shop.includes(:user, reviews: :user).find(params[:id])
    @shop_tags = @shop.tags
    @user = @shop.user
    @review = Review.new
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    tag_list = params[:shop][:tag_name].split(/[[:blank:]]+/)
    if @shop.save
      @shop.save_tag(tag_list)
      # params[:shop][:post_image].each do |a|
      #     @post_image = @shop.shop_images.create!(post_image: a, shop_id: @shop.id)
      # end
      redirect_to shops_path
    else
      render 'new'
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    unless user_signed_in? && current_user.id == @shop.user.id
      redirect_to action: :index
    end
  end

  def update
    @shop = Shop.find(params[:id])
    tag_list = params[:shop][:tag_name].split(/[[:blank:]]+/)
    if @shop.update(shop_params)
      @shop.save_tag(tag_list)
      redirect_to shop_path(@shop.id)
    else
      render 'edit'
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path
  end

  def search
    split_keyword = params[:keyword].split(/[[:blank:]]+/)
    @shops = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @shops += Shop.joins(tagmaps: :tag).where(["shop_name like? OR address like? OR tag_name like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    end
    @shops.uniq!
    @shops = Kaminari.paginate_array(@shops).page(params[:page])
    render 'index'
  end

  def rank
    @shops = Shop.all.includes(:reviews).order(rate_average: 'asc').page(params[:page]).reverse_order
    render 'index'
  end

  def hot
    @shops = Shop.joins(:reviews).where(created_at: Date.today.ago(7.days)..Date.today).group(:id).order("count(*) asc").page(params[:page]).reverse_order
    render 'index'
  end


  def tag_search
    @tag_list = Tag.includes(:tagmaps, tagmaps: :shop).all
    @tag = Tag.find(params[:tag_id])
    @shops = @tag.shops.includes(:tagmaps, tagmaps: :tag).all
  end

  private

  def shop_params
     params.require(:shop).permit(:shop_name, :shop_image, :introduction, :address, :tell, :holiday, :latitude, :longitude, :business_hours, post_images_images: [])
  end

end

app/controllers/user/tweet_comments_controller.rb
class User::TweetCommentsController < ApplicationController

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = current_user.tweet_comments.new(tweet_comment_params)
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet)
  end

  def destroy
    TweetComment.find_by(id: params[:id], tweet_id: params[:tweet_id]).destroy
    redirect_to tweet_path(params[:tweet_id])
  end

  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment)
  end
  
end

app/controllers/user/tweets_controller.rb
class User::TweetsController <User::ApplicationController

  def new
    @tweet = Tweet.new
  end

  def create
    @shop = Shop.new
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_back(fallback_location: root_path)
  end

private
  def tweet_params
    params.require(:tweet).permit(:user_id, :tweet)
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::ApplicationController

  def show
    @user = User.find(params[:id])
    @shops = @user.shops.includes(:reviews).all.order(created_at: "DESC")
    @bookmarks = Bookmark.includes(:shop,shop: :user).where(user_id: @user.id).page(params[:page]).per(8)
    @tweet = Tweet.new
    @tweets = Tweet.where(user_id: @user.following)
    @mytweets = Tweet.where(user_id: @user.id)
    @reviews = Review.includes(:user, :shop).where(user_id: @user).page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
    unless user_signed_in? && current_user.id == @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user.id)
      else
        render 'edit'
      end
  end

  def quit_confirm
  end

  def quit
    current_user.update(is_valid: false)
    sign_out(current_user)
  end

  def followings
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの編集はできません。'
    end
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/tweets/_index.html.erb
<div class="tweets_area" id='scroll_box'>
  <% tweets.includes(:user).order('updated_at DESC').each do |tweet|  %>
    <table class="table table-sm rounded border border-4 rounded">
      <td style="width: 20%" class="text-center">
        <%= link_to user_path(tweet.user), data: {"turbolinks" => false} do %>
        <%= attachment_image_tag tweet.user, :profile_image, size: '40x40', fallback: 'no_image.jpg', class: 'rounded-circle' %></br>
        <%= tweet.user.name %>さん</br>
        <p><%= tweet.created_at.strftime("%m/%d %H:%M:%S") %></p>
        <% end %>
      <td  style="width: 75%">
        <%= tweet.tweet %>
      </td>
      <td style="width: 5%">
        <% if tweet.liked_by?(current_user) %>
          <%= link_to tweet_likes_path(tweet), method: :delete do %>
            <i class="fas fa-heart"><%= tweet.likes.count %></i>
          <% end %>
        <% else %>
          <%= link_to tweet_likes_path(tweet), method: :post do %>
            <i class="far fa-heart"><%= tweet.likes.count %>
          <% end %>
        <% end %>
        <%= link_to tweet_path(tweet.id) do %>
          <i class="fas fa-comment"><%= "#{tweet.tweet_comments.count}" %></i> 
        <% end %>
        <% if current_user.id == tweet.user_id.to_i %>
          <%= link_to tweet_path(tweet.id), method: :delete, "data-confirm" => "本当に消しますか？" do %>
            <i class="fas fa-times-circle"></i>
          <% end %>
        <% end %>
      </td>
    </table>
  <% end %>
</div>

app/views/user/tweets/new.html.erb
<div class='container'>
  <div class="row g-3 mt-5">
    <div class="form-area col-lg-6 p-5 offset-md-3">
      <div class="page-title">New tweet</div>
        <div class='errors-area p-2'>
          <% if @tweet.errors.any? %>
            <%= @tweet.errors.count %>件のエラーが発生しました</br>
            <% @tweet.errors.full_messages.each do |message| %>
              <li>※&nbsp;<%= message %></li>
            <% end %>
          <% end %>
        </div>
        <div class="form">
          <%= form_with model: @tweet,local:true do |f| %>
            <div class="field form-group">
              <%= f.text_area :tweet, rows:'8', placeholder: "気軽につぶやこう！", size: "50", class: "form-control" %>
            </div>
            <div class='text-center'>
              <%= button_tag :method => :get, :class => "btn", onfocus: "this.blur();" do %>
                <span class= "col btnripple">
                  <i class="fas fa-paper-plane">&nbsp;投稿する</i>
                </span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/user/tweets/show.html.erb
<div class='container'>
  <%= render 'homes/top_link' %>
  <div class="row g-3">
    <div class="form-area col-lg-6 p-5 mx-auto">
      <div class="comments">
        
        <table class="table table-sm rounded border border-4 rounded">
          <td style="width: 20%" class="text-center">
            <%= link_to user_path(@tweet.user), data: {"turbolinks" => false} do %>
            <%= attachment_image_tag @tweet.user, :profile_image, size: '40x40', fallback: 'no_image.jpg', class: 'rounded-circle' %></br>
            <%= @tweet.user.name %>さん</br>
            <p><%= @tweet.created_at.strftime("%m/%d %H:%M:%S") %></p>
            <% end %>
          <td  style="width: 75%">
            <%= @tweet.tweet %>
          </td>
          <td style="width: 5%">
            <% if current_user.id == @tweet.user_id.to_i %>
              <%= link_to tweet_path(@tweet.id), method: :delete, "data-confirm" => "本当に消しますか？" do %>
                <i class="fas fa-times-circle"></i>
              <% end %>
            <% end %>
            <% if @tweet.liked_by?(current_user) %>
              <%= link_to tweet_likes_path(@tweet), method: :delete do %>
                <i class="fas fa-heart"><%= @tweet.likes.count %></i>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(@tweet), method: :post do %>
                <i class="far fa-heart"><%= @tweet.likes.count %>
              <% end %>
            <% end %>
             <p>
              <%= link_to tweet_path(@tweet.id) do %>
                <i class="fas fa-comment"><%= "#{@tweet.tweet_comments.count}" %></i> 
              <% end %>
             </p>
          </td>
        </table>
        <%= render 'user/tweet_comments/comment_form', tweet: @tweet, tweet_comment: @tweet_comment %>
      </div>
    </div>
  </div>
</div>